### ISSUE TITLE
Error when try to install vagrant-vbguest plugin

### ISSUE THREAD

**Issue by chetan19** [dotless-de/vagrant-vbguest#122]
Hello,

When I am trying to install

`vagrant plugin install vagrant-vbguest` plugin, it gives error.

```
Errors:

jignesh@jignesh-desktop:~/devstack$ sudo vagrant plugin install vagrant-vbguest
Installing the 'vagrant-vbguest' plugin. This can take a few minutes...
Building nokogiri using packaged libraries.
Building libxml2-2.8.0 for nokogiri with the following patches applied:
    - 0001-Fix-parser-local-buffers-size-problems.patch
    - 0002-Fix-entities-local-buffers-size-problems.patch
    - 0003-Fix-an-error-in-previous-commit.patch
    - 0004-Fix-potential-out-of-bound-access.patch
    - 0005-Detect-excessive-entities-expansion-upon-replacement.patch
    - 0006-Do-not-fetch-external-parsed-entities.patch
    - 0007-Enforce-XML_PARSER_EOF-state-handling-through-the-pa.patch
    - 0008-Improve-handling-of-xmlStopParser.patch
    - 0009-Fix-a-couple-of-return-without-value.patch
    - 0010-Keep-non-significant-blanks-node-in-HTML-parser.patch
    - 0011-Do-not-fetch-external-parameter-entities.patch
************************************************************************
IMPORTANT!  Nokogiri builds and uses a packaged version of libxml2.

If this is a concern for you and you want to use the system library
instead, abort this installation process and reinstall nokogiri as
follows:

    gem install nokogiri -- --use-system-libraries

If you are using Bundler, tell it to use the option:

    bundle config build.nokogiri --use-system-libraries
    bundle install

However, note that nokogiri does not necessarily support all versions
of libxml2.

For example, libxml2-2.9.0 and higher are currently known to be broken
and thus unsupported by nokogiri, due to compatibility problems and
XPath optimization bugs.
************************************************************************
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing nokogiri (1.6.2.1), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.6.2.1'` succeeds before bundling.

```

---

So when, I try to install `gem install nokogiri -v 1.6.2.1` it generate below error

```
Error:

jignesh@jignesh-desktop:~/devstack$ sudo gem install nokogiri -v 1.6.2.1
/usr/local/lib/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require': no such file to load -- net/https (LoadError)
    from /usr/local/lib/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/lib/site_ruby/1.9.1/rubygems/request.rb:39:in `configure_connection_for_https'
    from /usr/local/lib/site_ruby/1.9.1/rubygems/request.rb:93:in `connection_for'
    from /usr/local/lib/site_ruby/1.9.1/rubygems/request.rb:122:in `fetch'
    from /usr/local/lib/site_ruby/1.9.1/rubygems/remote_fetcher.rb:337:in `request'
    from /usr/local/lib/site_ruby/1.9.1/rubygems/remote_fetcher.rb:231:in `fetch_http'
    from /usr/local/lib/site_ruby/1.9.1/rubygems/remote_fetcher.rb:266:in `fetch_path'
    from /usr/local/lib/site_ruby/1.9.1/rubygems/remote_fetcher.rb:296:in `cache_update_path'
    from /usr/local/lib/site_ruby/1.9.1/rubygems/source.rb:177:in `load_specs'
    from /usr/local/lib/site_ruby/1.9.1/rubygems/spec_fetcher.rb:266:in `tuples_for'
    from /usr/local/lib/site_ruby/1.9.1/rubygems/spec_fetcher.rb:228:in `block in available_specs'
    from /usr/local/lib/site_ruby/1.9.1/rubygems/source_list.rb:97:in `each'
    from /usr/local/lib/site_ruby/1.9.1/rubygems/source_list.rb:97:in `each_source'
    from /usr/local/lib/site_ruby/1.9.1/rubygems/spec_fetcher.rb:222:in `available_specs'
    from /usr/local/lib/site_ruby/1.9.1/rubygems/spec_fetcher.rb:102:in `search_for_dependency'
    from /usr/local/lib/site_ruby/1.9.1/rubygems/dependency_installer.rb:216:in `find_gems_with_sources'
    from /usr/local/lib/site_ruby/1.9.1/rubygems/dependency_installer.rb:292:in `find_spec_by_name_and_version'
    from /usr/local/lib/site_ruby/1.9.1/rubygems/dependency_installer.rb:166:in `available_set_for'
    from /usr/local/lib/site_ruby/1.9.1/rubygems/dependency_installer.rb:418:in `resolve_dependencies'
    from /usr/local/lib/site_ruby/1.9.1/rubygems/dependency_installer.rb:371:in `install'
    from /usr/local/lib/site_ruby/1.9.1/rubygems/commands/install_command.rb:219:in `install_gem'
    from /usr/local/lib/site_ruby/1.9.1/rubygems/commands/install_command.rb:263:in `block in install_gems'
    from /usr/local/lib/site_ruby/1.9.1/rubygems/commands/install_command.rb:259:in `each'
    from /usr/local/lib/site_ruby/1.9.1/rubygems/commands/install_command.rb:259:in `install_gems'
    from /usr/local/lib/site_ruby/1.9.1/rubygems/commands/install_command.rb:171:in `execute'
    from /usr/local/lib/site_ruby/1.9.1/rubygems/command.rb:305:in `invoke_with_build_args'
    from /usr/local/lib/site_ruby/1.9.1/rubygems/command_manager.rb:167:in `process_args'
    from /usr/local/lib/site_ruby/1.9.1/rubygems/command_manager.rb:137:in `run'
    from /usr/local/lib/site_ruby/1.9.1/rubygems/gem_runner.rb:54:in `run'
    from /usr/bin/gem:21:in `<main>'

```

---

Can anyone please guide me to resolve this error.
I am using`ubuntu 10.04`
and `vagrant 1.6.2`

Thanks,
Chetan Parekh

**Comment by techquila** [comment]
it's actually a nokogiri issue.  

fix by running: gem update nokogiri
