### ISSUE TITLE
undefined method `group_by' for nil:NilClass

### ISSUE THREAD

**Issue by t1gor** [dotless-de/vagrant-vbguest#244]
Hi,

I have the following error while trying to install the plugin:

```bash
$ vagrant plugin install vagrant-vbguest
Installing the 'vagrant-vbguest' plugin. This can take a few minutes...
/usr/lib/ruby/2.3.0/rubygems/specification.rb:946:in `all=': undefined method `group_by' for nil:NilClass (NoMethodError)
	from /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb:275:in `with_isolated_gem'
	from /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb:231:in `internal_install'
	from /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb:102:in `install'
	from /usr/lib/ruby/vendor_ruby/vagrant/plugin/manager.rb:62:in `block in install_plugin'
	from /usr/lib/ruby/vendor_ruby/vagrant/plugin/manager.rb:72:in `install_plugin'
	from /usr/share/vagrant/plugins/commands/plugin/action/install_gem.rb:37:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builder.rb:116:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `block in run'
	from /usr/lib/ruby/vendor_ruby/vagrant/util/busy.rb:19:in `busy'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `run'
	from /usr/share/vagrant/plugins/commands/plugin/command/base.rb:14:in `action'
	from /usr/share/vagrant/plugins/commands/plugin/command/install.rb:32:in `block in execute'
	from /usr/share/vagrant/plugins/commands/plugin/command/install.rb:31:in `each'
	from /usr/share/vagrant/plugins/commands/plugin/command/install.rb:31:in `execute'
	from /usr/share/vagrant/plugins/commands/plugin/command/root.rb:56:in `execute'
	from /usr/lib/ruby/vendor_ruby/vagrant/cli.rb:42:in `execute'
	from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:268:in `cli'
	from /usr/bin/vagrant:173:in `<main>'
```

Versions info:
```# vagrant -v && ruby -v && lsb_release -d && VBoxManage -v```
- Vagrant 1.8.1
- ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
- OS: Ubuntu 16.04.1 LTS
- VirtualBox: 5.0.24_Ubuntur108355

Could you please point me to what am I doing wrong?

**Comment by fnordfish** [comment]
Hi  

No idea. Looks like purely vagrant internals to me. Can you try upgrading vagrant? IIRC 1.8 had some trouble with gem/plugin dependencies.  

--  
Robert Schulze

**Comment by agur** [comment]
Still getting a similar issue, any ideas?

```
$ vagrant plugin update vagrant-hostmanager
Updating plugins: vagrant-hostmanager. This may take a few minutes...
/usr/lib/ruby/2.3.0/rubygems/specification.rb:948:in `all=': undefined method `group_by' for nil:NilClass (NoMethodError)
	from /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb:275:in `with_isolated_gem'
	from /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb:231:in `internal_install'
	from /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb:149:in `update'
	from /usr/lib/ruby/vendor_ruby/vagrant/plugin/manager.rb:111:in `update_plugins'
	from /usr/share/vagrant/plugins/commands/plugin/action/update_gems.rb:23:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builder.rb:116:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `block in run'
	from /usr/lib/ruby/vendor_ruby/vagrant/util/busy.rb:19:in `busy'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `run'
	from /usr/share/vagrant/plugins/commands/plugin/command/base.rb:14:in `action'
	from /usr/share/vagrant/plugins/commands/plugin/command/update.rb:23:in `execute'
	from /usr/share/vagrant/plugins/commands/plugin/command/root.rb:56:in `execute'
	from /usr/lib/ruby/vendor_ruby/vagrant/cli.rb:42:in `execute'
	from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:268:in `cli'
	from /usr/bin/vagrant:173:in `<main>'
$ vagrant -v && ruby -v && lsb_release -d && VBoxManage -v
Vagrant 1.8.1
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
Description:	Linux Mint 18.3 Sylvia
5.0.40_Ubuntur115130
$ 
```

**Comment by p-alik** [comment]
I'm also looking for a solution
```
VBoxManage -v
Vagrant 1.8.1
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
Description:    Ubuntu 16.04.5 LTS
5.1.38_Ubuntur122592
```

**Comment by p-alik** [comment]
looks like it is an `Vagrant 1.8.1` issue.
I solved it by patching `lib/vagrant/bundler.rb` as described https://stackoverflow.com/a/36991648/2789312

**Comment by fnordfish** [comment]
Hey all, just out of curiosity: Is there a reason you stick with vagrant 1.8.1? I mean it was released December 21, 2015

**Comment by p-alik** [comment]
Ubuntu offers me only 1.8.1
```bash
$ apt-cache policy vagrant
vagrant:
  Installed: 1.8.1+dfsg-1ubuntu0.2
  Candidate: 1.8.1+dfsg-1ubuntu0.2
  Version table:
 *** 1.8.1+dfsg-1ubuntu0.2 500
        500 http://de.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages
        500 http://de.archive.ubuntu.com/ubuntu xenial-updates/universe i386 Packages
        100 /var/lib/dpkg/status
     1.8.1+dfsg-1 500
        500 http://de.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
        500 http://de.archive.ubuntu.com/ubuntu xenial/universe i386 Packages
```

**Comment by fnordfish** [comment]
oh wow, didn't know. thanks!

**Comment by richard-scott** [comment]
The Debian release works just fine on Ubuntu:
https://www.vagrantup.com/downloads.html
