### ISSUE TITLE
vagrant-vbguest (and ruby 3.0) gives `translate`: wrong number of arguments (given 2, expected 0..1)

### ISSUE THREAD

**Issue by basghar** [dotless-de/vagrant-vbguest#409]
`vagrant up` gives with following trace. So VM is booted but the shares do not work.

<details>
  <summary>i18n-1.8.7/lib/i18n.rb:195:in `translate': wrong number of arguments (Click to expand)</summary>

```
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
/usr/share/gems/gems/i18n-1.8.7/lib/i18n.rb:195:in `translate': wrong number of arguments (given 2, expected 0..1) (ArgumentError)
	from /home/babar/.vagrant.d/gems/3.0.1/gems/vagrant-vbguest-0.29.0/lib/vagrant-vbguest/middleware.rb:24:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/plugins/providers/virtualbox/action/customize.rb:40:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /home/babar/.vagrant.d/gems/3.0.1/gems/vagrant-hostsupdater-1.2.4/lib/vagrant-hostsupdater/Action/BaseAction.rb:34:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /home/babar/.vagrant.d/gems/3.0.1/gems/vagrant-hostsupdater-1.2.4/lib/vagrant-hostsupdater/Action/BaseAction.rb:34:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builder.rb:149:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `block in run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builtin/wait_for_communicator.rb:71:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/plugins/providers/virtualbox/action/customize.rb:40:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/plugins/providers/virtualbox/action/boot.rb:18:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/plugins/providers/virtualbox/action/customize.rb:40:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builtin/disk.rb:30:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builtin/cleanup_disks.rb:30:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /home/babar/.vagrant.d/gems/3.0.1/gems/vagrant-hostsupdater-1.2.4/lib/vagrant-hostsupdater/Action/BaseAction.rb:34:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /home/babar/.vagrant.d/gems/3.0.1/gems/vagrant-hostsupdater-1.2.4/lib/vagrant-hostsupdater/Action/BaseAction.rb:34:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builder.rb:149:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `block in run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/plugins/providers/virtualbox/action/sane_defaults.rb:38:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builtin/set_hostname.rb:17:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/plugins/providers/virtualbox/action/forward_ports.rb:31:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/plugins/providers/virtualbox/action/network_fix_ipv6.rb:41:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/plugins/providers/virtualbox/action/network.rb:123:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/plugins/providers/virtualbox/action/clear_network_interfaces.rb:26:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/plugins/providers/virtualbox/action/set_default_nic_type.rb:64:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/plugins/providers/virtualbox/action/prepare_nfs_settings.rb:19:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builtin/synced_folders.rb:87:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builtin/delayed.rb:19:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/plugins/synced_folders/nfs/action_cleanup.rb:25:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/plugins/providers/virtualbox/action/prepare_nfs_valid_ids.rb:12:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:52:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/plugins/providers/virtualbox/action/prepare_forwarded_port_collision_params.rb:30:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builtin/env_set.rb:19:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builtin/provision.rb:80:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/plugins/providers/virtualbox/action/clear_forwarded_ports.rb:15:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/plugins/providers/virtualbox/action/set_name.rb:19:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/plugins/providers/virtualbox/action/clean_machine_folder.rb:26:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /home/babar/.vagrant.d/gems/3.0.1/gems/vagrant-hostsupdater-1.2.4/lib/vagrant-hostsupdater/Action/BaseAction.rb:34:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /home/babar/.vagrant.d/gems/3.0.1/gems/vagrant-hostsupdater-1.2.4/lib/vagrant-hostsupdater/Action/BaseAction.rb:34:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builder.rb:149:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `block in run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /home/babar/.vagrant.d/gems/3.0.1/gems/vagrant-hostsupdater-1.2.4/lib/vagrant-hostsupdater/Action/BaseAction.rb:34:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /home/babar/.vagrant.d/gems/3.0.1/gems/vagrant-hostsupdater-1.2.4/lib/vagrant-hostsupdater/Action/BaseAction.rb:34:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builder.rb:149:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `block in run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /home/babar/.vagrant.d/gems/3.0.1/gems/vagrant-hostsupdater-1.2.4/lib/vagrant-hostsupdater/Action/BaseAction.rb:34:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /home/babar/.vagrant.d/gems/3.0.1/gems/vagrant-hostsupdater-1.2.4/lib/vagrant-hostsupdater/Action/BaseAction.rb:34:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builder.rb:149:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `block in run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builtin/box_check_outdated.rb:36:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/plugins/providers/virtualbox/action/check_virtualbox.rb:26:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /home/babar/.vagrant.d/gems/3.0.1/gems/vagrant-hostsupdater-1.2.4/lib/vagrant-hostsupdater/Action/BaseAction.rb:34:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /home/babar/.vagrant.d/gems/3.0.1/gems/vagrant-hostsupdater-1.2.4/lib/vagrant-hostsupdater/Action/BaseAction.rb:34:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builder.rb:149:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `block in run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /home/babar/.vagrant.d/gems/3.0.1/gems/vagrant-hostsupdater-1.2.4/lib/vagrant-hostsupdater/Action/BaseAction.rb:34:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /home/babar/.vagrant.d/gems/3.0.1/gems/vagrant-hostsupdater-1.2.4/lib/vagrant-hostsupdater/Action/BaseAction.rb:34:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builder.rb:149:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `block in run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/plugins/providers/virtualbox/action/discard_state.rb:15:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /home/babar/.vagrant.d/gems/3.0.1/gems/vagrant-hostsupdater-1.2.4/lib/vagrant-hostsupdater/Action/BaseAction.rb:34:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /home/babar/.vagrant.d/gems/3.0.1/gems/vagrant-hostsupdater-1.2.4/lib/vagrant-hostsupdater/Action/BaseAction.rb:34:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builder.rb:149:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `block in run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/plugins/providers/virtualbox/action/check_virtualbox.rb:26:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /home/babar/.vagrant.d/gems/3.0.1/gems/vagrant-hostsupdater-1.2.4/lib/vagrant-hostsupdater/Action/BaseAction.rb:34:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /home/babar/.vagrant.d/gems/3.0.1/gems/vagrant-hostsupdater-1.2.4/lib/vagrant-hostsupdater/Action/BaseAction.rb:34:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builder.rb:149:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `block in run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/plugins/providers/virtualbox/action/check_virtualbox.rb:26:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /home/babar/.vagrant.d/gems/3.0.1/gems/vagrant-hostsupdater-1.2.4/lib/vagrant-hostsupdater/Action/BaseAction.rb:34:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/builder.rb:149:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `block in run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/machine.rb:246:in `action_raw'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/machine.rb:215:in `block in action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/environment.rb:614:in `lock'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/machine.rb:201:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/machine.rb:201:in `action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/plugins/commands/reload/command.rb:42:in `block in execute'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/plugin/v2/command.rb:243:in `block in with_target_vms'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/plugin/v2/command.rb:232:in `each'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/plugin/v2/command.rb:232:in `with_target_vms'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/plugins/commands/reload/command.rb:40:in `execute'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/cli.rb:67:in `execute'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/lib/vagrant/environment.rb:290:in `cli'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.16/bin/vagrant:231:in `<top (required)>'
	from /usr/share/vagrant/gems/bin/vagrant:23:in `load'
	from /usr/share/vagrant/gems/bin/vagrant:23:in `<main>'
```
</details>

*Environment:*
```
❯ vagrant --version
Vagrant 2.2.16
❯ vagrant plugin list    
vagrant-hostsupdater (1.2.4, global)
vagrant-libvirt (0.4.1, system)
vagrant-vbguest (0.29.0, global)
❯ ruby -v
ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]

Distributor ID:	Fedora
Description:	Fedora release 34 (Thirty Four)
Release:	34
```

**Comment by mattock** [comment]
Same problem here

```
$ vagrant --version
Vagrant 2.2.16
$ vagrant plugin list
rexml (3.2.5, global)
vagrant-hostmanager (1.8.9, global)
vagrant-vbguest (0.29.0, global)
winrm (2.3.6, global)
winrm-elevated (1.2.3, global)
winrm-fs (1.3.5, global)
$ ruby -v
ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]
$ cat /etc/redhat-release 
Fedora release 34 (Thirty Four)
```

**Comment by basghar** [comment]
> It is possible to "vagrant up" a VM that uses vagrant-vbguest. But things like vboxfs mounts do not work.
Yes that is correct. Updated the issue description

**Comment by fnordfish** [comment]
Just to understand, vagrant on Fedora (all linux?) does not ship with a bundled version but depends on what ruby you have in your env?

Vagrants [gemspec](https://github.com/hashicorp/vagrant/blob/main/vagrant.gemspec#L15) defines a ruby version `"~> 2.5", "< 2.8"`, and the macOS version ships with `ruby 2.6.7p197`.

I'll try to make up some time and see where vagrant-vbguest might be incompatible with ruby3, but don't expect anything fast.

I suggest installing a second ruby 2.6 (maybe 2.7 if you like, which should print those type of errors as warning) to run your vagrant on.

**Comment by mattock** [comment]
The "translate" function in I18n no longer takes parameters in the same way as before. Here's a trivial patch that at least gets vagrant-vbguest going:
```
samuli@carbon:~/.vagrant.d/gems/3.0.1/gems/vagrant-vbguest-0.29.0/lib/vagrant-vbguest$ diff -u middleware.rb.orig middleware.rb
--- middleware.rb.orig  2021-06-01 11:39:43.868888703 +0300
+++ middleware.rb       2021-06-01 11:40:15.795901071 +0300
@@ -21,7 +21,7 @@
       if options[:auto_update]
         machine = VagrantVbguest::Machine.new vm, options
         status  = machine.state
-        vm.env.ui.send((:ok == status ? :success : :warn), I18n.t("vagrant_vbguest.status.#{status}", machine.info))
+        vm.env.ui.send((:ok == status ? :success : :warn), I18n.t("vagrant_vbguest.status.#{status}"))
         machine.run
         reboot(vm, options) if machine.reboot?
       end
```
The translate method in I18n has quite a long description including warnings about breaking changes in Ruby 3.0 (=the one in Fedora 34):

* https://github.com/ruby-i18n/i18n/blob/master/lib/i18n.rb#L196

**Comment by fnordfish** [comment]
If `I18n.t` is the only issue, that'd be an easy change (if `machine.info` produces symbol keys)

```diff
-        vm.env.ui.send((:ok == status ? :success : :warn), I18n.t("vagrant_vbguest.status.#{status}", machine.info))
+        vm.env.ui.send((:ok == status ? :success : :warn), I18n.t("vagrant_vbguest.status.#{status}", **machine.info))
```

This KeyWord-Argument change in ruby3 causes breaking ruby libs all over the place, so I assume that won't be the last one. Hence, I'd need to investigate.

**Comment by mattock** [comment]
Vagrant-vbguest started working after my hack. But I don't know if that covered all the corner-cases.
